// <auto-generated />
using System;
using CodeSmith.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeSmith.Infrastructure.Migrations
{
    [DbContext(typeof(CodeSmithDbContext))]
    [Migration("20260807045533_AddFreeTokensCoveredToUsageLedger")]
    partial class AddFreeTokensCoveredToUsageLedger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeSmith.Core.Models.Usage.CreditBalance", b =>
                {
                    b.Property<string>("ObjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("FreeQuotaMax")
                        .HasColumnType("bigint");

                    b.Property<long>("FreeTokensUsed")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PaidCreditsBalance")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ObjectId");

                    b.HasIndex("ObjectId");

                    b.ToTable("CreditBalances");
                });

            modelBuilder.Entity("CodeSmith.Core.Models.Usage.IpFreeUsage", b =>
                {
                    b.Property<string>("Ip")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("FreeTokensIssued")
                        .HasColumnType("bigint");

                    b.HasKey("Ip");

                    b.HasIndex("Ip");

                    b.ToTable("IpFreeUsages");
                });

            modelBuilder.Entity("CodeSmith.Core.Models.Usage.ProcessedStripeEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ProcessedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("EventId");

                    b.ToTable("ProcessedStripeEvents");
                });

            modelBuilder.Entity("CodeSmith.Core.Models.Usage.UsageLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Feature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FreeTokensCovered")
                        .HasColumnType("int");

                    b.Property<int>("InputTokens")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("int");

                    b.Property<int?>("Provider")
                        .HasColumnType("int");

                    b.Property<decimal?>("ProviderCostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("ObjectId", "TimestampUtc");

                    b.ToTable("UsageLedgerEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
