// == LLM Response Model == //
namespace CodeSmith.Core.Models;

/// <summary>
/// Provider-agnostic response returned by any ILlmService implementation.
/// </summary>
public class LlmResponse
{
    public string Content { get; set; } = string.Empty;   // The text content of the model's response
    public int InputTokensUsed { get; set; }              // Number of input tokens consumed by this call
    public int OutputTokensUsed { get; set; }             // Number of output tokens generated by this call (for usage + cost)
    public string Model { get; set; } = string.Empty;     // Exact model used for this call (e.g. fast or accurate name) — required for accurate costing
    public int ContextWindowSize { get; set; }            // Total context window size for the model used
    public bool WasTruncated { get; set; }                // True when the provider stopped early due to the token limit
}
